INSERT INTO COURSE (ID, NAME, CREATED_DATE, LAST_UPDATED_DATE) 
VALUES(10001, 'JPA in 50 Steps', SYSDATE(), SYSDATE());
INSERT INTO COURSE (ID, NAME, CREATED_DATE, LAST_UPDATED_DATE) 
VALUES(10002, 'HIBERNATE in 30 Steps', SYSDATE(), SYSDATE());
INSERT INTO COURSE (ID, NAME, CREATED_DATE, LAST_UPDATED_DATE) 
VALUES(10003, 'SPRINGBOOT in 100 Steps', SYSDATE(), SYSDATE());
INSERT INTO COURSE (ID, NAME, CREATED_DATE, LAST_UPDATED_DATE) 
VALUES(10004, 'MySQL in 11 Steps', SYSDATE(), SYSDATE());